name: $(Version).$(rev:r)

trigger:
  branches:
    include:
    - release/*

pr: none

variables:
- group: Common
- name: TestRunStatus
  value: ''

stages:
- stage: BuildTestAndPublish
  displayName: 'Build and Test'

  jobs:
  - job: WindowsLatest
    displayName: 'Hosted Windows Latest'

    pool:
      vmImage: 'windows-latest'

    workspace:
      clean: all

    steps:
    - template: 'template-steps-build-test.yaml'
    - template: 'template-steps-publish.yaml'

- stage: Release
  displayName: 'Release to NuGet'

  jobs:
  - template: 'template-job-release.yaml'
